blog/views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from flask_login import login_required
from datetime import datetime

from . import db
from .models import Content, Tag, ContentAndTag
from .blog import Blog

import json

views = Blueprint("views", __name__)

def show_blogs(search="", tag_id=None, role=None):
    list_blogs = []
    if tag_id == None:
        if role == None:
            all_contents = Content.query.filter(Content.data.like('%'+search+'%'), Content.private == 0).order_by(Content.id.desc()).all()
        else:
            all_contents = Content.query.filter(Content.data.like('%'+search+'%')).order_by(Content.id.desc()).all()
        for content in all_contents:
            list_tags = []
            all_content_and_tag = ContentAndTag.query.filter_by(content_id=content.id).all()
            for content_and_tag in all_content_and_tag:
                tag = Tag.query.filter_by(id=content_and_tag.tag_id).first()
                list_tags.append(tag.name_tag)
            blog = Blog(content.id, content.title, content.private, content.data, content.date, list_tags)
            list_blogs.append(blog)

    else:
        filter_contentAndTags = ContentAndTag.query.filter_by(tag_id=tag_id).order_by(ContentAndTag.id.desc()).all()
        for contentAndTag in filter_contentAndTags:
            content = Content.query.filter_by(id=contentAndTag.content_id).first()
            if role == None:
                if content.private == 1:
                    continue
            list_tags = []
            all_content_and_tag = ContentAndTag.query.filter_by(content_id=content.id).all()
            for content_and_tag in all_content_and_tag:
                tag = Tag.query.filter_by(id=content_and_tag.tag_id).first()
                list_tags.append(tag.name_tag)
            blog = Blog(content.id, content.title, content.private, content.data, content.date, list_tags)
            list_blogs.append(blog)
    
    return list_blogs

def show_tags():
    list_tags = []
    all_tags = Tag.query.all()
    for tag in all_tags:
        list_tags.append(tag)

    return list_tags

@views.route("/index")
@views.route("/")
def guest():
    return render_template("index.html", list_blogs=show_blogs(), list_tags=show_tags())

@views.route("/admin")
@login_required
def admin():
    return render_template("admin.html", list_blogs=show_blogs(role="admin"), list_tags=show_tags())

@views.route("/add", methods=["GET", "POST"])
@login_required
def add():
    if request.method == "POST":
        title = request.form.get("title")
        data = request.form.get("data")
        private = request.form.get("private")
        tags = request.form.get("tags")
        tag_list = tags.replace(" ", "").split(",")

        if private == "1":
            private = True
        else:
            private = False

        new_content = Content(title=title, data=data, private=private, date=datetime.now())
        db.session.add(new_content)
        db.session.commit()

        content_new_id = Content.query.order_by(Content.id.desc()).first().id
        for name_tag in tag_list:
            tag = Tag.query.filter_by(name_tag=name_tag).first()
            if not tag:
                new_tag = Tag(name_tag=name_tag)
                db.session.add(new_tag)
                db.session.commit()
                new_tag_id = Tag.query.order_by(Tag.id.desc()).first().id
                new_contentAndTag = ContentAndTag(content_id=content_new_id, tag_id=new_tag_id)
            else:
                new_contentAndTag = ContentAndTag(content_id=content_new_id, tag_id=tag.id)
            db.session.add(new_contentAndTag)
            db.session.commit()

    return redirect(url_for("views.admin"))

@views.route("/update", methods=["GET", "POST"])
@login_required
def update():
    if request.method == "POST":
        content_id = request.form.get("content_id")
        title = request.form.get("title")
        data = request.form.get("data")
        private = request.form.get("private")
        tags = request.form.get("tags")
        tag_list = tags.replace(" ", "").split(",")
        
        if private == "1":
            private = True
        else:
            private = False

        content_update = Content.query.filter_by(id=content_id).first()
        if content_update:
            content_update.title = title
            content_update.data = data
            content_update.private = private
            content_update.date = datetime.now()
            db.session.commit()

        contentAndTags_delete = ContentAndTag.query.filter_by(content_id=content_id).all()
        for contentAndTag in contentAndTags_delete:
            count_tag = ContentAndTag.query.filter_by(tag_id=contentAndTag.tag_id).count()
            if count_tag == 1:
                delete_tag = Tag.query.filter_by(id=contentAndTag.tag_id).first()
                db.session.delete(delete_tag)
            db.session.delete(contentAndTag)
        db.session.commit()

        for name_tag in tag_list:
            tag = Tag.query.filter_by(name_tag=name_tag).first()
            if not tag:
                new_tag = Tag(name_tag=name_tag)
                db.session.add(new_tag)
                db.session.commit()
                new_tag_id = Tag.query.order_by(Tag.id.desc()).first().id
                new_contentAndTag = ContentAndTag(content_id=content_id, tag_id=new_tag_id)
            else:
                new_contentAndTag = ContentAndTag(content_id=content_id, tag_id=tag.id)
            db.session.add(new_contentAndTag)
            db.session.commit()
    
    return redirect(url_for("views.admin"))

@views.route("/delete", methods=["GET", "POST"])
@login_required
def delete():
    blog = json.loads(request.data)
    blog_id = blog["blog_id"]

    contentAndTags_delete = ContentAndTag.query.filter_by(content_id=blog_id).all()
    for contentAndTag in contentAndTags_delete:
        count_tag = ContentAndTag.query.filter_by(tag_id=contentAndTag.tag_id).count()
        if count_tag == 1:
            delete_tag = Tag.query.filter_by(id=contentAndTag.tag_id).first()
            db.session.delete(delete_tag)
        db.session.delete(contentAndTag)

    content = Content.query.filter_by(id=blog_id).first()
    db.session.delete(content)
    db.session.commit()

    return jsonify({"code": 200})

@views.route("/search_in_admin", methods=["GET", "POST"])
@login_required
def search_in_admin():
    if request.method == "POST":
        text = request.form.get("search")
        print(text)
    return render_template("admin.html", list_blogs=show_blogs(text, role="admin"), list_tags=show_tags())

@views.route("/search_in_guest", methods=["GET", "POST"])
def search_in_guest():
    if request.method == "POST":
        text = request.form.get("search")
        print(text)
    return render_template("index.html", list_blogs=show_blogs(text), list_tags=show_tags())

@views.route("/filter_in_admin", methods=["GET", "POST"])
@login_required
def filter_in_admin():
    tag_id = request.args.get('tag_id')
    return render_template("admin.html", list_blogs=show_blogs(tag_id=tag_id, role="admin"), list_tags=show_tags())

@views.route("/filter_in_guest", methods=["GET", "POST"])
def filter_in_guest():
    tag_id = request.args.get('tag_id')
    return render_template("index.html", list_blogs=show_blogs(tag_id=tag_id), list_tags=show_tags())

blog/templates/admin.html
{% extends "base.html" %}

{% block title %} Admin {% endblock %}

{% block header %}
    <div class="logo"><a href="/admin">Blog</a></div>
        <form action="{{ url_for('views.search_in_admin') }}" method="POST" class="search-bar">
            <input type="text" placeholder="Search..." name="search">
            <button type="submit" class="search-btn">Search</button>
        </form>
        <a href="/logout">Log Out</a>
{% endblock %}


{% block tag %}
    <h2>List Tags</h2>
    {% for tag in list_tags %}
        <p><a href="/filter_in_admin?tag_id={{ tag.id }}">{{ tag.name_tag }}</a></p>
    {% endfor %}
{% endblock %}

{% block content %}
    {% for blog in list_blogs %}
        <div class="blog">
            <div class="blog-header">
                <h2>{{ blog.title }}</h2>
                {% if blog.private %}
                    <p class="private-indicator"><em>Private</em></p>
                {% endif %}
                <p class="blog-date">{{ blog.date.strftime("%d/%m/%Y %H:%M") }}</p>
            </div>
            <div class="blog-content">
                <pre>{{ blog.data }}</pre>
            </div>
            <div class="blog-tags">
                {% for tag in blog.list_tags %}
                    <span class="tag">{{ tag }}</span>
                {% endfor %}
            </div>
            <div class="blog-actions">
                <button class="edit-btn" onclick="toggleEditNoteForm('{{ blog.id }}')">Edit</button>
                <button class="delete-btn" onclick="deleteBlog('{{ blog.id }}')">Delete</button>
            </div>
        </div>    
        
        <!-- Edit Form -->
        <div id="{{ blog.id }}" class="edit-note-form">
            <div class="form-content">
                <span class="close-btn" onclick="toggleEditNoteForm('{{ blog.id }}')">&times;</span>
                <h2>Edit Blog</h2>
                <form action="{{ url_for('views.update') }}" method="POST">
                    <input type="hidden" value="{{ blog.id }}" name="content_id">
                    <input type="text" placeholder="Title" value="{{ blog.title }}" name="title">
                    <br>
                    <textarea placeholder="Content" name="data">{{ blog.data }}</textarea>
                    <br>
                    <input type="text" placeholder="Tags (comma separated)" value="{% for tag in blog.list_tags %}{{ tag }}{% if not loop.last %}, {% endif %}{% endfor %}" name="tags">
                    <br>
                    <label><input type="radio" name="private" value="1" {% if blog.private %}checked{% endif %}>Private</label>
                    <label><input type="radio" name="private" value="0" {% if not blog.private %}checked{% endif %}>Public</label>
                    <button type="submit">Update</button>
                </form>
            </div>
        </div>
    {% endfor %}
{% endblock %}

{% block addNote %}
    <button id="addNoteButton" class="add-note-btn" onclick="toggleAddNoteForm()">+</button>
    <div id="addNoteForm" class="add-note-form">
        <div class="form-content">
            <span class="close-btn" onclick="toggleAddNoteForm()">&times;</span>
            <h2>Add Blog</h2>
            <form action="{{ url_for('views.add') }}" method="POST">
                <input type="text" placeholder="Title" name="title">
                <textarea placeholder="Content" name="data"></textarea>
                <input type="text" placeholder="Tags (comma separated)" name="tags">
                <br>
                <label><input type="radio" name="private" value="1">Private</label>
                <label><input type="radio" name="private" value="0" checked>Public</label>
                <br>
                <button type="submit">Add</button>
            </form>
        </div>
    </div>
{% endblock %}

blog/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %} {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
</head>
<body>
    <header>
        <nav>
            {% block header %} {% endblock %}
        </nav>
    </header>

    {% block login %}
    {% endblock %}

    <!-- Content -->
    <div class="container">
        <aside class="sidebar">
            {% block tag %}
            {% endblock %}
        </aside>
        <main class="content">
            {% block content %}
            {% endblock %}
        </main>
        
        {% block addNote %}
        {% endblock %}
    <script type="text/javascript" src="{{ url_for('static', filename='base.js') }}"></script>
</body>
</html>

blog/templates/index.html
{% extends "base.html" %}

{% block title %} Blog {% endblock %}

{% block header %}
    <div class="logo"><a href="/">Blog</a></div>
        <form action="{{ url_for('views.search_in_guest') }}" method="POST" class="search-bar">
            <input type="text" placeholder="Search..." name="search">
            <button type="submit" class="search-btn">Search</button>
        </form>
    <p style="cursor: pointer;" onclick="toggleLoginForm()">Log In</p>
{% endblock %}

{% block login %}
    <!-- Popup form -->
    <div id="login-form" class="login-form">
        <div class="login-form-content">
            <span class="close-btn" onclick="toggleLoginForm()">&times;</span>
            <h2>Login</h2>
            <form action="{{ url_for('user.login')}}" method="POST">
                <input type="text" placeholder="Username" name="username">
                <input type="password" placeholder="Password" name="password">
                <button type="submit">Login</button>
            </form>
        </div>
    </div>
{% endblock %}

{% block tag %}
    <h2>List Tags</h2>
    {% for tag in list_tags %}
        <p><a href="/filter_in_guest?tag_id={{ tag.id }}">{{ tag.name_tag }}</a></p>
    {% endfor %}
{% endblock %}

{% block content %}
    {% for blog in list_blogs %}
        <div class="blog">
            <div class="blog-header">
                <h2>{{ blog.title }}</h2>
                <p class="blog-date">{{ blog.date.strftime("%d/%m/%Y %H:%M") }}</p>
            </div>
            <div class="blog-content">
                <pre>{{ blog.data }}</pre>
            </div>
            <div class="blog-tags">
                {% for tag in blog.list_tags %}
                    <span class="tag">{{ tag }}</span>
                {% endfor %}
            </div>
        </div>
    {% endfor %}
{% endblock %}